from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
PACKAGE_ROOT = ROOT / "examples" / "production_packages"
OUTPUT = ROOT / "docs" / "sample_gallery.md"


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def read_asset_count(path: Path) -> int:
    if not path.exists():
        return 0
    with path.open(encoding="utf-8", newline="") as handle:
        return len(list(csv.DictReader(handle)))


def read_quality(package_dir: Path) -> tuple[str, str, str]:
    quality_path = package_dir / "quality_review.md"
    if not quality_path.exists():
        return "C", "keep_manifest_only", "No quality_review.md yet."
    text = quality_path.read_text(encoding="utf-8")
    grade = "C"
    recommendation = "review_required"
    for line in text.splitlines():
        lower = line.lower()
        if lower.startswith("- quality grade:"):
            grade = line.split(":", 1)[1].strip().strip("`")
        if lower.startswith("- retention recommendation:"):
            recommendation = line.split(":", 1)[1].strip().strip("`")
    return grade, recommendation, quality_path.relative_to(ROOT).as_posix()


def package_row(package_dir: Path) -> dict[str, str]:
    run_manifest_path = package_dir / "run_manifest.json"
    run_manifest = read_json(run_manifest_path) if run_manifest_path.exists() else {"package_id": package_dir.name}
    grade, recommendation, quality_ref = read_quality(package_dir)
    files = {
        "preview": package_dir / "preview.html",
        "source_manifest": package_dir / "source_manifest.json",
        "asset_manifest": package_dir / "asset_manifest.csv",
        "sync_timeline": package_dir / "sync_timeline.json",
        "montage_timeline": package_dir / "montage_timeline.json",
        "privacy_check": package_dir / "privacy_check.md",
        "render_report": package_dir / "render_report.md",
        "recipe": package_dir / "recipe.md",
    }
    return {
        "package_id": str(run_manifest.get("package_id", package_dir.name)),
        "created_at": str(run_manifest.get("created_at", "unknown")),
        "quality_grade": grade,
        "retention": recommendation,
        "asset_count": str(read_asset_count(files["asset_manifest"])),
        **{key: (value.relative_to(ROOT).as_posix() if value.exists() else "missing") for key, value in files.items()},
        "quality_review": quality_ref,
    }


def build_markdown(rows: list[dict[str, str]]) -> str:
    lines = [
        "# Sample Gallery and Production Package Index",
        "",
        "This index lists reviewable packages and points to manifests, previews, quality reviews, and retention decisions. It is generated by `python scripts/workflow/build_sample_gallery.py`.",
        "",
        "| Package | Grade | Retention | Preview | Source | Assets | Timeline | Privacy | Render | Recipe |",
        "|---|---:|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        def link(label: str, path: str) -> str:
            return "missing" if path == "missing" else f"[{label}](../{path})"

        timeline_path = row["sync_timeline"] if row["sync_timeline"] != "missing" else row["montage_timeline"]
        lines.append(
            "| {package_id} | {quality_grade} | {retention} | {preview} | {source} | {assets} | {sync} | {privacy} | {render} | {recipe} |".format(
                package_id=row["package_id"],
                quality_grade=row["quality_grade"],
                retention=row["retention"],
                preview=link("preview", row["preview"]),
                source=link("source", row["source_manifest"]),
                assets=link("assets", row["asset_manifest"]),
                sync=link("timeline", timeline_path),
                privacy=link("privacy", row["privacy_check"]),
                render=link("render", row["render_report"]),
                recipe=link("recipe", row["recipe"]),
            )
        )
    lines.extend([
        "",
        "## Retention guidance",
        "",
        "- Keep `A` and `B` packages as reproducible fixtures when rights and privacy notes are clear.",
        "- Keep `C` packages as manifest/diagnostic references only; do not promote as good samples.",
        "- Do not commit large MP4/WebM/raw public-video files unless a separate storage policy explicitly allows it.",
    ])
    return "\n".join(lines) + "\n"


def main() -> int:
    rows = [package_row(path) for path in sorted(PACKAGE_ROOT.iterdir()) if path.is_dir()]
    OUTPUT.write_text(build_markdown(rows), encoding="utf-8")
    print(json.dumps({"event": "sample_gallery_written", "output": str(OUTPUT), "packages": len(rows)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
