from __future__ import annotations

import argparse
import csv
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_TOPIC_BRIEF = ROOT / "examples" / "topic_briefs" / "short-video-scale-makes-evidence-first-ai-video-workflows-necessary_20260705T000000Z.json"
DEFAULT_OUTPUT_ROOT = ROOT / "examples" / "production_packages"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build an offline, review-gated production package from a topic brief fixture.")
    parser.add_argument("--topic-brief", default=str(DEFAULT_TOPIC_BRIEF), help="Topic brief JSON generated by topic discovery.")
    parser.add_argument("--package-id", required=True, help="Unique slug_timestamp package id; existing package is not overwritten unless --force is set.")
    parser.add_argument("--output-root", default=str(DEFAULT_OUTPUT_ROOT), help="Root directory for production packages.")
    parser.add_argument("--git-commit", help="Git commit to write into run_manifest.json. Defaults to current HEAD.")
    parser.add_argument("--force", action="store_true", help="Allow regenerating an existing package directory.")
    return parser.parse_args()


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def git_commit() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception:
        return "unknown"


def timestamp_to_created_at(value: str) -> str:
    timestamp = value.rsplit("_", 1)[-1]
    try:
        return datetime.strptime(timestamp, "%Y%m%dT%H%M%SZ").replace(tzinfo=timezone.utc).isoformat().replace("+00:00", "Z")
    except ValueError:
        return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def source_manifest(package_id: str, brief: dict[str, Any]) -> dict[str, Any]:
    sources = []
    for candidate in brief["source_candidates"]:
        source_id = candidate["title"].lower().replace(" ", "_").replace("/", "_")[:64]
        sources.append(
            {
                "id": source_id,
                "title": candidate["title"],
                "source_type": candidate["source_type"],
                "url_or_path": candidate["url"],
                "priority": candidate["priority"],
                "evidence_expected": candidate["evidence_expected"],
                "capture_mode": "offline_fixture",
                "review_status": "needs_human_source_confirmation_before_public_release",
            }
        )
    return {"package_id": package_id, "topic": brief["topic"], "discovery_mode": brief["discovery_mode"], "sources": sources}


def asset_rows() -> list[dict[str, str]]:
    return [
        {
            "asset_id": "cnnic_report_pdf_fixture",
            "asset_type": "pdf",
            "path": "examples/source_capture/official_sources/cnnic_55_statistical_report.pdf",
            "origin": "offline_fixture",
            "public_commit_allowed": "true",
            "license_notes": "Fixture for internal evidence demo; verify official source URL before publication.",
            "risk_notes": "No personal data; external release still needs rights review.",
        },
        {
            "asset_id": "cnnic_page_40_screenshot",
            "asset_type": "image",
            "path": "examples/source_capture/official_source_screenshots/cnnic_55_report_page_40.png",
            "origin": "offline_fixture",
            "public_commit_allowed": "true",
            "license_notes": "Small checked-in screenshot fixture for reproducible source zoom.",
            "risk_notes": "Use only as internal fixture until fresh capture URL is confirmed.",
        },
        {
            "asset_id": "cnnic_bbox",
            "asset_type": "json",
            "path": "examples/mainline_v4_sync/cnnic_pdf_bbox.json",
            "origin": "derived_fixture",
            "public_commit_allowed": "true",
            "license_notes": "Derived bbox metadata.",
            "risk_notes": "Review cue alignment before render approval.",
        },
    ]


def write_asset_manifest(path: Path) -> None:
    rows = asset_rows()
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def sync_timeline(package_id: str, brief: dict[str, Any]) -> dict[str, Any]:
    return {
        "package_id": package_id,
        "composition_id": "EvidenceSourceZoomDemo",
        "spec": {"width": 1080, "height": 1920, "fps": 30, "duration_seconds": 20},
        "events": [
            {
                "start_ms": 0,
                "end_ms": 3000,
                "event_type": "hook",
                "voiceover_text": brief["hook"],
                "evidence_id": "cnnic_report_pdf_fixture",
                "review_status": "draft",
            },
            {
                "start_ms": 3000,
                "end_ms": 9500,
                "event_type": "source_zoom",
                "voiceover_text": "Use the official report line as the claim-bearing evidence, then zoom to the exact bbox.",
                "evidence_id": "cnnic_page_40_screenshot",
                "bbox_path": "examples/mainline_v4_sync/cnnic_pdf_bbox.json",
                "camera_action": "zoom_to_pdf_line_and_highlight",
                "review_status": "needs_human_fact_check",
            },
            {
                "start_ms": 9500,
                "end_ms": 20000,
                "event_type": "interpretation",
                "voiceover_text": brief["video_angle"],
                "evidence_id": "cnnic_report_pdf_fixture",
                "review_status": "draft",
            },
        ],
    }


def write_text_reports(package_dir: Path, package_id: str, brief: dict[str, Any]) -> None:
    (package_dir / "privacy_check.md").write_text(
        f"# Privacy Check\n\n"
        f"- Package: `{package_id}`\n"
        "- Public-reference video: none included.\n"
        "- Faces/accounts/comments/QR codes: none intentionally included.\n"
        "- Privacy mask requirement before public-video insertion: face, account, caption, QR, comment, and logo review.\n"
        "- Current residual risk: low for internal fixture package; public release not approved.\n",
        encoding="utf-8",
    )
    (package_dir / "render_report.md").write_text(
        f"# Render Report\n\n"
        f"- Package: `{package_id}`\n"
        "- Render mode: offline package preview; no mp4 render attempted by this builder.\n"
        "- Intended Remotion composition: `EvidenceSourceZoomDemo`, 1080x1920, 30 fps, 20 seconds.\n"
        "- Fallback output: `preview.html` and manifests for review when browser/ffmpeg are unavailable.\n"
        "- Review gate: human approval required before publish or live-source recapture.\n",
        encoding="utf-8",
    )
    (package_dir / "preview.html").write_text(
        "<!doctype html>\n"
        "<meta charset=\"utf-8\">\n"
        f"<title>{package_id} evidence preview</title>\n"
        "<style>body{font-family:system-ui,sans-serif;max-width:960px;margin:40px auto;line-height:1.5} code{background:#eee;padding:2px 4px} .card{border:1px solid #ccc;padding:16px;margin:12px 0}</style>\n"
        f"<h1>{brief['topic']}</h1>\n"
        f"<p><strong>Hook:</strong> {brief['hook']}</p>\n"
        f"<p><strong>Review gate:</strong> human review required before capture/render/publication.</p>\n"
        "<div class=\"card\"><h2>Evidence fixture</h2><p><code>examples/source_capture/official_source_screenshots/cnnic_55_report_page_40.png</code></p></div>\n"
        "<div class=\"card\"><h2>Manifests</h2><ul><li>source_manifest.json</li><li>asset_manifest.csv</li><li>sync_timeline.json</li><li>privacy_check.md</li><li>render_report.md</li></ul></div>\n",
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()
    topic_brief_path = Path(args.topic_brief)
    output_root = Path(args.output_root)
    package_dir = output_root / args.package_id
    if package_dir.exists() and not args.force:
        raise FileExistsError(f"Package already exists: {package_dir}. Use --force only for deterministic fixture regeneration.")
    package_dir.mkdir(parents=True, exist_ok=True)
    brief = read_json(topic_brief_path)

    write_json(package_dir / "source_manifest.json", source_manifest(args.package_id, brief))
    write_asset_manifest(package_dir / "asset_manifest.csv")
    write_json(package_dir / "sync_timeline.json", sync_timeline(args.package_id, brief))
    write_text_reports(package_dir, args.package_id, brief)
    write_json(
        package_dir / "run_manifest.json",
        {
            "package_id": args.package_id,
            "created_at": timestamp_to_created_at(args.package_id),
            "git_commit": args.git_commit or git_commit(),
            "topic_brief": str(topic_brief_path.relative_to(ROOT) if topic_brief_path.is_relative_to(ROOT) else topic_brief_path),
            "review_gate": "human_review_required_before_publish",
            "paths": {
                "source_manifest": "source_manifest.json",
                "asset_manifest": "asset_manifest.csv",
                "sync_timeline": "sync_timeline.json",
                "privacy_check": "privacy_check.md",
                "render_report": "render_report.md",
                "preview": "preview.html",
            },
            "large_or_local_assets_committed": False,
            "public_reference_original_video_committed": False,
            "digital_avatar_assets_committed": False,
        },
    )
    print(json.dumps({"event": "offline_package_written", "package_dir": str(package_dir), "package_id": args.package_id}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
