import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';

const workspaceRoot = process.cwd();
const outputPath = path.join(workspaceRoot, 'work', 'local_cookies', 'douyin_public_session_cookies.txt');
const seedUrl = 'https://www.douyin.com/video/7604404119343877403';

const browser = await chromium.launch({headless: true});
const context = await browser.newContext({
  viewport: {width: 1440, height: 900},
  locale: 'zh-CN',
  timezoneId: 'Asia/Shanghai',
  userAgent:
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
});
const page = await context.newPage();
await page.goto(seedUrl, {waitUntil: 'domcontentloaded', timeout: 60000});
await page.waitForTimeout(9000);
const cookies = await context.cookies();
await browser.close();

const netscape = [
  '# Netscape HTTP Cookie File',
  '# Generated by the public Douyin page probe. Not a user login cookie jar.',
  ...cookies.map((cookie) => {
    const domain = cookie.domain.startsWith('.') ? cookie.domain : cookie.domain;
    const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const pathValue = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.expires && cookie.expires > 0 ? Math.floor(cookie.expires) : 0;
    return [domain, includeSubdomains, pathValue, secure, expires, cookie.name, cookie.value].join('\t');
  }),
].join('\n');

await fs.mkdir(path.dirname(outputPath), {recursive: true});
await fs.writeFile(outputPath, `${netscape}\n`, 'utf8');
console.log(JSON.stringify({event: 'douyin_public_cookies_exported', output: outputPath, count: cookies.length}));
